<?php
//error_reporting(0);
ini_set('memory_limit', '-1');

include('koneksi.php');
include('koneksi_sipeg.php');
require '../vendor/autoload.php';
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

$blth2 = $_REQUEST['blth'];

$tempdir = "temp/"; 
if (!file_exists($tempdir))
    mkdir($tempdir);

//PLNT    
$spreadsheet = new Spreadsheet();
$spreadsheet->setActiveSheetIndex(0);
$sheet = $spreadsheet->getActiveSheet();
$sheet->setTitle('PLNT');
$sheet->getStyle('A1:AT1')->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID)->getStartColor()->setARGB('FFb5b1b1');
$sheet->getStyle('A1:AT1')->getAlignment()->setWrapText(true);
$sheet->getStyle("A1:AT1")->applyFromArray([
    "alignment" => [
        "vertical" => \PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_TOP,
        "horizontal" => \PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER
    ],
]);

$sheet->getColumnDimension('A')->setWidth(5);
$sheet->getColumnDimension('B')->setWidth(15);
$sheet->getColumnDimension('C')->setWidth(25);
$sheet->getColumnDimension('D')->setWidth(15);
$sheet->getColumnDimension('E')->setWidth(15);
$sheet->getColumnDimension('F')->setWidth(15);
$sheet->getColumnDimension('G')->setWidth(15);
$sheet->getColumnDimension('H')->setWidth(15);
$sheet->getColumnDimension('I')->setWidth(15);
$sheet->getColumnDimension('J')->setWidth(15);
$sheet->getColumnDimension('K')->setWidth(15);
$sheet->getColumnDimension('L')->setWidth(15);
$sheet->getColumnDimension('M')->setWidth(15);
$sheet->getColumnDimension('N')->setWidth(15);
$sheet->getColumnDimension('O')->setWidth(15);
$sheet->getColumnDimension('P')->setWidth(15);
$sheet->getColumnDimension('Q')->setWidth(15);
$sheet->getColumnDimension('R')->setWidth(15);
$sheet->getColumnDimension('S')->setWidth(15);
$sheet->getColumnDimension('T')->setWidth(15);
$sheet->getColumnDimension('U')->setWidth(15);
$sheet->getColumnDimension('V')->setWidth(15);
$sheet->getColumnDimension('W')->setWidth(15);
$sheet->getColumnDimension('X')->setWidth(15);
$sheet->getColumnDimension('Y')->setWidth(15);
$sheet->getColumnDimension('Z')->setWidth(15);
$sheet->getColumnDimension('AA')->setWidth(15);
$sheet->getColumnDimension('AB')->setWidth(15);
$sheet->getColumnDimension('AC')->setWidth(15);
$sheet->getColumnDimension('AD')->setWidth(15);
$sheet->getColumnDimension('AE')->setWidth(15);
$sheet->getColumnDimension('AF')->setWidth(15);
$sheet->getColumnDimension('AG')->setWidth(15);
$sheet->getColumnDimension('AH')->setWidth(15);
$sheet->getColumnDimension('AI')->setWidth(15);
$sheet->getColumnDimension('AJ')->setWidth(15);
$sheet->getColumnDimension('AK')->setWidth(15);
$sheet->getColumnDimension('AL')->setWidth(15);
$sheet->getColumnDimension('AM')->setWidth(15);
$sheet->getColumnDimension('AN')->setWidth(15);
$sheet->getColumnDimension('AO')->setWidth(15);
$sheet->getColumnDimension('AP')->setWidth(15);
$sheet->getColumnDimension('AQ')->setWidth(15);
$sheet->getColumnDimension('AR')->setWidth(15);
$sheet->getColumnDimension('AS')->setWidth(15);
$sheet->getColumnDimension('AT')->setWidth(25);

$alignment_center = \PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER;
$alignment_center2 = \PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER;

$sheet->setCellValue('A1', 'No');
$sheet->setCellValue('B1', 'NIP');
$sheet->setCellValue('C1', 'Nama');
$sheet->setCellValue('D1', 'Gaji Dasar');
$sheet->setCellValue('E1', 'Honorarium');
$sheet->setCellValue('F1', 'Honorer');
$sheet->setCellValue('G1', 'Tarif Grade (P1)');
$sheet->setCellValue('H1', 'P2-1A');
$sheet->setCellValue('I1', 'P2-1B');
$sheet->setCellValue('J1', 'Tunj.Lokasi');
$sheet->setCellValue('K1', 'Tunj.Perumahan');
$sheet->setCellValue('L1', 'Tunj.Transportasi');
$sheet->setCellValue('M1', 'Bantuan Pulsa');
$sheet->setCellValue('N1', 'Lembur');
$sheet->setCellValue('O1', 'Tunjangan Lain');
$sheet->setCellValue('P1', 'Total Pendapatan');
$sheet->setCellValue('Q1', 'DPLK Persero');
$sheet->setCellValue('R1', 'DPLK Simponi Perusahaan');
$sheet->setCellValue('S1', 'JP');
$sheet->setCellValue('T1', 'JKM');
$sheet->setCellValue('U1', 'JKK');
$sheet->setCellValue('V1', 'JHT');
$sheet->setCellValue('W1', 'Kes');
$sheet->setCellValue('X1', 'Benefit');
$sheet->setCellValue('Y1', 'Pendapatan+Benefit');
$sheet->setCellValue('Z1', 'Pot.Koperasi');
$sheet->setCellValue('AA1', 'Pot.Bazis');
$sheet->setCellValue('AB1', 'Pot DPLK Simponi');
$sheet->setCellValue('AC1', 'Pot DPLK Pribadi');
$sheet->setCellValue('AD1', 'COP Kendaraan');
$sheet->setCellValue('AE1', 'Iuran Peserta');
$sheet->setCellValue('AF1', 'BRPR');
$sheet->setCellValue('AG1', 'Sewa Mess');
$sheet->setCellValue('AH1', 'Pot.Qurban');
$sheet->setCellValue('AI1', 'Pot.Arisan');
$sheet->setCellValue('AJ1', 'Pot.JP');
$sheet->setCellValue('AK1', 'Pot.JHT');
$sheet->setCellValue('AL1', 'Pot.Kes');
$sheet->setCellValue('AM1', 'Potongan Lain');
$sheet->setCellValue('AN1', 'Total Potongan');
$sheet->setCellValue('AO1', 'Dibayarkan');
$sheet->setCellValue('AP1', 'NPWP');
$sheet->setCellValue('AQ1', 'KPP');
$sheet->setCellValue('AR1', 'Bank');
$sheet->setCellValue('AS1', 'Rekening');
$sheet->setCellValue('AT1', 'Atas Nama');

$gaji_dasar2 = 0;
$honorarium2 = 0;
$honorer2 = 0;
$tarif_grade2 = 0;
$tunjangan_posisi2 = 0;
$p21b2 = 0;
$tunjangan_kemahalan2 = 0;
$tunjangan_perumahan2 = 0;
$tunjangan_transportasi2 = 0;
$bantuan_pulsa2 = 0;
$dplk_persero2 = 0;
$dplk_simponi_pr2 = 0;
$lembur2 = 0;
$tunjangan_lain2 = 0;
$bpjs_tk_pp2 = 0;
$bpjs_tk_kp2 = 0;
$bpjs_tk_kkp2 = 0;
$bpjs_tk_htp2 = 0;
$bpjs_tk_jhtk2 = 0;
$bpjs_tk_pk2 = 0;
$bpjs_kes_pp2 = 0;
$bpjs_kes_pk2 = 0;
$total_pendapatan2 = 0;
$bpjs_pr2 = 0;
$benefit2 = 0;
$pendapatan_benefit2 = 0;
$pot_koperasi2 = 0;
$pot_bazis2 = 0;
$dplk_simponi2 = 0;
$pot_dplk_pribadi2 = 0;
$cop_kendaraan2 = 0;
$iuran_peserta2 = 0;
$brpr2 = 0;
$sewa_mess2 = 0;
$qurban2 = 0;
$arisan2 = 0;
$potongan_lain2 = 0;
$total_potongan2 = 0;
$pph212 = 0;
$upah_bersih2 = 0;

$i = 2;
$no = 1;
$rs = mysqli_query($koneksi,"select a.*,b.nama_lengkap from organikplnt.gaji a left join hrisnew.data_pegawai b on a.nip=b.nip where a.blth='$blth2' and a.jenis<>'ORGANIK' and a.jenis<>'TUGAS KARYA' and a.jenis<>'TUGAS KERJA' order by a.id asc");
while ($hasil = mysqli_fetch_array($rs)){
    $id = stripslashes ($hasil['id']);
    $blth = stripslashes ($hasil['blth']);
    $nip = stripslashes ($hasil['nip']);
    $nama_lengkap = stripslashes ($hasil['nama_lengkap']);
    $npwp = stripslashes ($hasil['npwp']);
    $kpp = stripslashes ($hasil['kpp']);
    $jenis = stripslashes ($hasil['jenis']);
    $gaji_dasar = floatval(stripslashes ($hasil['gaji_dasar']));
    $honorarium = floatval(stripslashes ($hasil['honorarium']));
    $honorer = floatval(stripslashes ($hasil['honorer']));
    $tarif_grade = floatval(stripslashes ($hasil['tarif_grade']));
    $tunjangan_posisi = floatval(stripslashes ($hasil['tunjangan_posisi']));
    $p21b = floatval(stripslashes ($hasil['p21b']));
    $tunjangan_kemahalan = floatval(stripslashes ($hasil['tunjangan_kemahalan']));
    $tunjangan_perumahan = floatval(stripslashes ($hasil['tunjangan_perumahan']));
    $tunjangan_transportasi = floatval(stripslashes ($hasil['tunjangan_transportasi']));
    $bantuan_pulsa = floatval(stripslashes ($hasil['bantuan_pulsa']));
    $dplk_persero = floatval(stripslashes ($hasil['dplk_persero']));
    $dplk_simponi_pr = floatval(stripslashes ($hasil['dplk_simponi_pr']));
    $lembur = floatval(stripslashes ($hasil['lembur']));
    $nama_tunjangan1 = stripslashes ($hasil['nama_tunjangan1']);
    $tunjangan1 = floatval(stripslashes ($hasil['tunjangan1']));
    $nama_tunjangan2 = stripslashes ($hasil['nama_tunjangan2']);
    $tunjangan2 = floatval(stripslashes ($hasil['tunjangan2']));
    $nama_tunjangan3 = stripslashes ($hasil['nama_tunjangan3']);
    $tunjangan3 = floatval(stripslashes ($hasil['tunjangan3']));
    $nama_tunjangan4 = stripslashes ($hasil['nama_tunjangan4']);
    $tunjangan4 = floatval(stripslashes ($hasil['tunjangan4']));
    $tunjangan_lain = $tunjangan1+$tunjangan2+$tunjangan3+$tunjangan4;
    $bpjs_tk_pp = floatval(stripslashes ($hasil['bpjs_tk_pp']));
    $bpjs_tk_kp = floatval(stripslashes ($hasil['bpjs_tk_kp']));
    $bpjs_tk_kkp = floatval(stripslashes ($hasil['bpjs_tk_kkp']));
    $bpjs_tk_htp = floatval(stripslashes ($hasil['bpjs_tk_htp']));
    $bpjs_tk_jhtk = floatval(stripslashes ($hasil['bpjs_tk_jhtk']));
    $bpjs_tk_pk = floatval(stripslashes ($hasil['bpjs_tk_pk']));
    $bpjs_kes_pp = floatval(stripslashes ($hasil['bpjs_kes_pp']));
    $bpjs_kes_pk = floatval(stripslashes ($hasil['bpjs_kes_pk']));
    $total_pendapatan = floatval(stripslashes ($hasil['total_pendapatan']));
    $bpjs_pr = floatval(stripslashes ($hasil['bpjs_pr']));
    $benefit = floatval(stripslashes ($hasil['benefit']));        
    $pendapatan_benefit = floatval(stripslashes ($hasil['pendapatan_benefit']));        
    $pot_koperasi = floatval(stripslashes ($hasil['pot_koperasi']));        
    $pot_bazis = floatval(stripslashes ($hasil['pot_bazis']));        
    $dplk_simponi = floatval(stripslashes ($hasil['dplk_simponi']));        
    $pot_dplk_pribadi = floatval(stripslashes ($hasil['pot_dplk_pribadi']));        
    $cop_kendaraan = floatval(stripslashes ($hasil['cop_kendaraan']));
    $iuran_peserta = floatval(stripslashes ($hasil['iuran_peserta']));
    $brpr = floatval(stripslashes ($hasil['brpr']));
    $sewa_mess = floatval(stripslashes ($hasil['sewa_mess']));
    $qurban = floatval(stripslashes ($hasil['qurban']));
    $arisan = floatval(stripslashes ($hasil['arisan']));
    $nama_potongan1 = stripslashes ($hasil['nama_potongan1']);
    $potongan1 = floatval(stripslashes ($hasil['potongan1']));
    $nama_potongan2 = stripslashes ($hasil['nama_potongan2']);
    $potongan2 = floatval(stripslashes ($hasil['potongan2']));
    $nama_potongan3 = stripslashes ($hasil['nama_potongan3']);
    $potongan3 = floatval(stripslashes ($hasil['potongan3']));
    $nama_potongan4 = stripslashes ($hasil['nama_potongan4']);
    $potongan4 = floatval(stripslashes ($hasil['potongan4']));
    $potongan_lain = $potongan1+$potongan2+$potongan3+$potongan4;
    $total_potongan = floatval(stripslashes ($hasil['total_potongan']));
    $pph21 = floatval(stripslashes ($hasil['pph21']));
    $upah_bersih = floatval(stripslashes ($hasil['upah_bersih']));
    $bank_payroll = stripslashes ($hasil['bank_payroll']);
    $no_rek_payroll = stripslashes ($hasil['no_rek_payroll']);
    $an_payroll = stripslashes ($hasil['an_payroll']);

    $gaji_dasar2 = $gaji_dasar2+$gaji_dasar;
    $honorarium2 = $honorarium2+$honorarium;
    $honorer2 = $honorer2+$honorer;
    $tarif_grade2 = $tarif_grade2+$tarif_grade;
    $tunjangan_posisi2 = $tunjangan_posisi2+$tunjangan_posisi;
    $p21b2 = $p21b2+$p21b;
    $tunjangan_kemahalan2 = $tunjangan_kemahalan2+$tunjangan_kemahalan;
    $tunjangan_perumahan2 = $tunjangan_perumahan2+$tunjangan_perumahan;
    $tunjangan_transportasi2 = $tunjangan_transportasi2+$tunjangan_transportasi;
    $bantuan_pulsa2 = $bantuan_pulsa2+$bantuan_pulsa;
    $dplk_persero2 = $dplk_persero2+$dplk_persero;
    $dplk_simponi_pr2 = $dplk_simponi_pr2+$dplk_simponi_pr;
    $lembur2 = $lembur2+$lembur;
    $tunjangan_lain2 = $tunjangan_lain2+$tunjangan_lain;
    $bpjs_tk_pp2 = $bpjs_tk_pp2+$bpjs_tk_pp;
    $bpjs_tk_kp2 = $bpjs_tk_kp2+$bpjs_tk_kp;
    $bpjs_tk_kkp2 = $bpjs_tk_kkp2+$bpjs_tk_kkp;
    $bpjs_tk_htp2 = $bpjs_tk_htp2+$bpjs_tk_htp;
    $bpjs_tk_jhtk2 = $bpjs_tk_jhtk2+$bpjs_tk_jhtk;
    $bpjs_tk_pk2 = $bpjs_tk_pk2+$bpjs_tk_pk;
    $bpjs_kes_pp2 = $bpjs_kes_pp2+$bpjs_kes_pp;
    $bpjs_kes_pk2 = $bpjs_kes_pk2+$bpjs_kes_pk;
    $total_pendapatan2 = $total_pendapatan2+$total_pendapatan;
    $bpjs_pr2 = $bpjs_pr2+$bpjs_pr;
    $benefit2 = $benefit2+$benefit;
    $pendapatan_benefit2 = $pendapatan_benefit2+$pendapatan_benefit;
    $pot_koperasi2 = $pot_koperasi2+$pot_koperasi;
    $pot_bazis2 = $pot_bazis2+$pot_bazis;
    $dplk_simponi2 = $dplk_simponi2+$dplk_simponi;
    $pot_dplk_pribadi2 = $pot_dplk_pribadi2+$pot_dplk_pribadi;
    $cop_kendaraan2 = $cop_kendaraan2+$cop_kendaraan;
    $iuran_peserta2 = $iuran_peserta2+$iuran_peserta;
    $brpr2 = $brpr2+$brpr;
    $sewa_mess2 = $sewa_mess2+$sewa_mess;
    $qurban2 = $qurban2+$qurban;
    $arisan2 = $arisan2+$arisan;
    $potongan_lain2 = $potongan_lain2+$potongan_lain;
    $total_potongan2 = $total_potongan2+$total_potongan;
    $pph212 = $pph212+$pph21;
    $upah_bersih2 = $upah_bersih2+$upah_bersih;

    $spreadsheet->getActiveSheet()->getStyle('D'.$i.':AQ'.$i)->getNumberFormat()->setFormatCode('#,##0');
    $spreadsheet->getActiveSheet()->getStyle('AP'.$i.':AT'.$i)->getNumberFormat()->setFormatCode(\PhpOffice\PhpSpreadsheet\Style\NumberFormat::FORMAT_TEXT);
    $sheet->getStyle('A'.$i.':AT'.$i)->applyFromArray([
        "alignment" => [
            "vertical" => \PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_TOP
        ],
    ]);

    $sheet->setCellValue('A'.$i, $no);
    $sheet->setCellValue('B'.$i, $nip);
    $sheet->setCellValue('C'.$i, $nama_lengkap);
    $sheet->setCellValue('D'.$i, $gaji_dasar);
    $sheet->setCellValue('E'.$i, $honorarium);
    $sheet->setCellValue('F'.$i, $honorer);
    $sheet->setCellValue('G'.$i, $tarif_grade);
    $sheet->setCellValue('H'.$i, $tunjangan_posisi);
    $sheet->setCellValue('I'.$i, $p21b);
    $sheet->setCellValue('J'.$i, $tunjangan_kemahalan);
    $sheet->setCellValue('K'.$i, $tunjangan_perumahan);
    $sheet->setCellValue('L'.$i, $tunjangan_transportasi);
    $sheet->setCellValue('M'.$i, $bantuan_pulsa);
    $sheet->setCellValue('N'.$i, $lembur);
    $sheet->setCellValue('O'.$i, $tunjangan_lain);
    $sheet->setCellValue('P'.$i, $total_pendapatan);
    $sheet->setCellValue('Q'.$i, $dplk_persero);
    $sheet->setCellValue('R'.$i, $dplk_simponi_pr);
    $sheet->setCellValue('S'.$i, $bpjs_tk_pp);
    $sheet->setCellValue('T'.$i, $bpjs_tk_kp);
    $sheet->setCellValue('U'.$i, $bpjs_tk_kkp);
    $sheet->setCellValue('V'.$i, $bpjs_tk_htp);
    $sheet->setCellValue('W'.$i, $bpjs_kes_pp);
    $sheet->setCellValue('X'.$i, $benefit);
    $sheet->setCellValue('Y'.$i, $pendapatan_benefit);
    $sheet->setCellValue('Z'.$i, $pot_koperasi);
    $sheet->setCellValue('AA'.$i, $pot_bazis);
    $sheet->setCellValue('AB'.$i, $dplk_simponi);
    $sheet->setCellValue('AC'.$i, $pot_dplk_pribadi);
    $sheet->setCellValue('AD'.$i, $cop_kendaraan);
    $sheet->setCellValue('AE'.$i, $iuran_peserta);
    $sheet->setCellValue('AF'.$i, $brpr);
    $sheet->setCellValue('AG'.$i, $sewa_mess);
    $sheet->setCellValue('AH'.$i, $qurban);
    $sheet->setCellValue('AI'.$i, $arisan);
    $sheet->setCellValue('AJ'.$i, $bpjs_tk_pk);
    $sheet->setCellValue('AK'.$i, $bpjs_tk_jhtk);
    $sheet->setCellValue('AL'.$i, $bpjs_kes_pk);
    $sheet->setCellValue('AM'.$i, $potongan_lain);
    $sheet->setCellValue('AN'.$i, $total_potongan);
    $sheet->setCellValue('AO'.$i, $upah_bersih);
    $sheet->setCellValue('AP'.$i, $npwp);
    $sheet->setCellValue('AQ'.$i, $kpp);
    $sheet->setCellValue('AR'.$i, $bank_payroll);
    $sheet->setCellValue('AS'.$i, $no_rek_payroll);
    $sheet->setCellValue('AT'.$i, $an_payroll);
    $i++;
    $no = $no+1;
}
$sheet->getStyle('A'.$i.':AT'.$i)->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID)->getStartColor()->setARGB('FFb5b1b1');
$spreadsheet->getActiveSheet()->getStyle('D'.$i.':AQ'.$i)->getNumberFormat()->setFormatCode('#,##0');
$spreadsheet->getActiveSheet()->getStyle('AP'.$i.':AT'.$i)->getNumberFormat()->setFormatCode(\PhpOffice\PhpSpreadsheet\Style\NumberFormat::FORMAT_TEXT);
$sheet->setCellValue('A'.$i, "");
$sheet->setCellValue('B'.$i, "");
$sheet->setCellValue('C'.$i, "TOTAL");
$sheet->setCellValue('D'.$i, $gaji_dasar2);
$sheet->setCellValue('E'.$i, $honorarium2);
$sheet->setCellValue('F'.$i, $honorer2);
$sheet->setCellValue('G'.$i, $tarif_grade2);
$sheet->setCellValue('H'.$i, $tunjangan_posisi2);
$sheet->setCellValue('I'.$i, $p21b2);
$sheet->setCellValue('J'.$i, $tunjangan_kemahalan2);
$sheet->setCellValue('K'.$i, $tunjangan_perumahan2);
$sheet->setCellValue('L'.$i, $tunjangan_transportasi2);
$sheet->setCellValue('M'.$i, $bantuan_pulsa2);
$sheet->setCellValue('N'.$i, $lembur2);
$sheet->setCellValue('O'.$i, $tunjangan_lain2);
$sheet->setCellValue('P'.$i, $total_pendapatan2);
$sheet->setCellValue('Q'.$i, $dplk_persero2);
$sheet->setCellValue('R'.$i, $dplk_simponi_pr2);
$sheet->setCellValue('S'.$i, $bpjs_tk_pp2);
$sheet->setCellValue('T'.$i, $bpjs_tk_kp2);
$sheet->setCellValue('U'.$i, $bpjs_tk_kkp2);
$sheet->setCellValue('V'.$i, $bpjs_tk_htp2);
$sheet->setCellValue('W'.$i, $bpjs_kes_pp2);
$sheet->setCellValue('X'.$i, $benefit2);
$sheet->setCellValue('Y'.$i, $pendapatan_benefit2);
$sheet->setCellValue('Z'.$i, $pot_koperasi2);
$sheet->setCellValue('AA'.$i, $pot_bazis2);
$sheet->setCellValue('AB'.$i, $dplk_simponi2);
$sheet->setCellValue('AC'.$i, $pot_dplk_pribadi2);
$sheet->setCellValue('AD'.$i, $cop_kendaraan2);
$sheet->setCellValue('AE'.$i, $iuran_peserta2);
$sheet->setCellValue('AF'.$i, $brpr2);
$sheet->setCellValue('AG'.$i, $sewa_mess2);
$sheet->setCellValue('AH'.$i, $qurban2);
$sheet->setCellValue('AI'.$i, $arisan2);
$sheet->setCellValue('AJ'.$i, $bpjs_tk_pk2);
$sheet->setCellValue('AK'.$i, $bpjs_tk_jhtk2);
$sheet->setCellValue('AL'.$i, $bpjs_kes_pk2);
$sheet->setCellValue('AM'.$i, $potongan_lain2);
$sheet->setCellValue('AN'.$i, $total_potongan2);
$sheet->setCellValue('AO'.$i, $upah_bersih2);
$sheet->setCellValue('AP'.$i, "");
$sheet->setCellValue('AQ'.$i, "");
$sheet->setCellValue('AR'.$i, "");
$sheet->setCellValue('AS'.$i, "");
$sheet->setCellValue('AT'.$i, "");

//$spreadsheet->setActiveSheetIndex(0);
header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
header('Content-Disposition: attachment; filename="Gaji Honor.xlsx"'); // Set nama file excel nya
header('Cache-Control: max-age=0');

$writer = new Xlsx($spreadsheet);
$writer->save('php://output');

?>